FROM ruby:3.3-alpine

RUN apk add --no-cache git build-base ruby-dev

WORKDIR /srv/jekyll

ARG USER
ARG BLOG_URL
ARG GIT_TOKEN


RUN git config --global url."https://${GIT_TOKEN}@github.com/".insteadOf "https://github.com/" \
    && git clone https://github.com/${USER}/${BLOG_URL} .
    
RUN addgroup -S jekyll && adduser -S jekyll -G jekyll \
    && chown -R jekyll:jekyll /srv/jekyll \
    && chmod -R u+w /srv/jekyll

USER jekyll:jekyll

RUN bundle install

COPY start.sh ./start.sh
