FROM ruby:3.3-alpine

RUN apk add --no-cache git build-base ruby-dev

WORKDIR /srv/jekyll
COPY . .

## 변경할 곳
ENV USER NeatyNut
ENV BLOG_URL neatynut.github.io

ENV GIT_URL https://github.com/${USER}/${BLOG_URL}.git
RUN git clone $GIT_URL
RUN addgroup -S jekyll && adduser -S jekyll -G jekyll
RUN sh -c "chown -R jekyll:jekyll /srv/jekyll"
RUN sh -c "chmod -R u+w /srv/jekyll"
EXPOSE 4000
RUN sh -c "cd /srv/jekyll/$BLOG_URL && bundle install"