FROM jupyter/tensorflow-notebook:x86_64-ubuntu-22.04

WORKDIR /app

ARG USER
ARG GIT_TOKEN

RUN git config --global url."https://${GIT_TOKEN}@github.com/".insteadOf "https://github.com/" \
    && git clone https://github.com/${USER}/rotto.git .