FROM python:3.13-slim

WORKDIR /app

RUN apt-get update && apt-get install -y git tzdata \
    && ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime \
    && echo "Asia/Seoul" > /etc/timezone \
    && dpkg-reconfigure -f noninteractive tzdata

RUN git clone https://github.com/NeatyNut/Exchange_Rate_Search_Bot.git
COPY credentials.json /app/Exchange_Rate_Search_Bot/credentials.json
COPY .env /app/Exchange_Rate_Search_Bot/.env

RUN python3 -m venv /app/venv
RUN /bin/bash -c "source /app/venv/bin/activate && pip install --upgrade pip && pip install --no-cache-dir -r /app/Exchange_Rate_Search_Bot/requirement.txt"
ENV PATH="/app/venv/bin:$PATH"